# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ping.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nping.proto\x12\x11hypergrpc.ping.v1\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tPongReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa6\x01\n\x0bPingService\x12\x44\n\x04Ping\x12\x1e.hypergrpc.ping.v1.PingRequest\x1a\x1c.hypergrpc.ping.v1.PongReply\x12Q\n\x0fUnaryStreamPing\x12\x1e.hypergrpc.ping.v1.PingRequest\x1a\x1c.hypergrpc.ping.v1.PongReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=33
  _globals['_PINGREQUEST']._serialized_end=63
  _globals['_PONGREPLY']._serialized_start=65
  _globals['_PONGREPLY']._serialized_end=93
  _globals['_PINGSERVICE']._serialized_start=96
  _globals['_PINGSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
